In [1]:
# Gerekli kütüphaneler
import tensorflow as tf
import librosa

In [2]:
# Model parametreleri
input_size = 128
hidden_size = 256
output_size = 2
batch_size = 64

In [3]:
# Modeli oluştur
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(None, input_size), batch_size=batch_size),
    tf.keras.layers.LSTM(hidden_size,kernel_regularizer=tf.keras.regularizers.L2()),
    tf.keras.layers.Dense(output_size, activation='linear',kernel_regularizer=tf.keras.regularizers.L2())
])

In [ ]:
# Parametereleri yükle
model.load_weights("Checkpoints/cp.weights.h5")

In [4]:
# Veri setinden tr ses dosyası al
audio, sample_rate = librosa.load("Datasets/tr/clips/common_voice_tr_17344860.mp3")
audio_feature = librosa.feature.melspectrogram(y=audio*2, sr=sample_rate)
tensor_x = tf.transpose(tf.convert_to_tensor(audio_feature, dtype=tf.float32))

In [5]:
# Batch size ekle
tensor_x = tf.expand_dims(tensor_x, axis=0)

In [6]:
# Tensor boyutuna bak
tensor_x.shape

TensorShape([1, 181, 128])

In [7]:
# Tahmin et
prediction = model.predict(tensor_x)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 376ms/step


array([[-1.9164075,  2.2078073]], dtype=float32)

In [8]:
# Veri setinden zh-CN ses dosyası al
audio, sample_rate = librosa.load("Datasets/zh-CN/clips/common_voice_zh-CN_18524189.mp3")
melspectrogram = librosa.feature.melspectrogram(y=audio, sr=sample_rate)
tensor_x = tf.transpose(tf.convert_to_tensor(melspectrogram, dtype=tf.float32))

In [9]:
# Batch size ekle
tensor_x = tf.expand_dims(tensor_x, axis=0)

In [10]:
# Tensor boyutuna bak
tensor_x.shape

TensorShape([1, 140, 128])

In [11]:
# Tahmin et
prediction = model.predict(tensor_x)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step


array([[-1.8649372,  2.1740415]], dtype=float32)

In [12]:
# Test ses dosyası al
audio, sample_rate = librosa.load("test.mp3")
audio = audio * 2
import IPython.display as display
display.Audio(audio, rate=sample_rate)

In [13]:
# Sesi işle
audio_feature = librosa.feature.melspectrogram(y=audio, sr=sample_rate)
tensor_x = tf.transpose(tf.convert_to_tensor(audio_feature, dtype=tf.float32))

In [14]:
# Batch size ekle
tensor_x = tf.expand_dims(tensor_x, axis=0)

In [15]:
# Tensor boyutuna bak
tensor_x.shape

TensorShape([1, 169, 128])

In [16]:
# Tahmin et
prediction = model.predict(tensor_x)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step


array([[-1.9223588,  2.2209132]], dtype=float32)